Repository MTES-MCT/action-bidonvilles-api, pull requests merged in 2021-05, with the labels that each got.

#78 #patch (?) Migration vers l'API de soliguide
  db/migrations/000108-01-drop-table-poi.js
  server/controllers/poiController.js
  server/models/poiModel.js
Labels: [à review]

#80 #patch (834) date de signalement site obligatoire plutôt que date d'installation
  server/middlewares/validators/common/writeTown.js
Labels: [qa]

#73 #patch (916) Rendre les statistiques privées accessible aux admin locaux
  db/migrations/000107-alter-table-permissions-stats-read-local-admin.js
Labels: [qa]

#72 #patch (915) Création du rôle observer (observateur)
  db/migrations/000107-01-insert-intervener-permissions.js
Labels: [qa]

#88 #patch (1023) Ajout Pop-up de nouveautés 0.16.0
  assets/changelog/0.16.0/search-name-h400.gif
  assets/changelog/0.16.0/sort-name-h400.gif
  db/seeders/000000-changelog-0.16.0.js
Labels: [en attente de review]

#90 #patch (hotfix) La feature `stats.read` n'est pas inséré par les migrations
  db/migrations/000054-02-populate-entities.js
  db/migrations/000055-02-populate-features.js
  db/migrations/000062-09-create-table-stats_permissions.js
Labels: [validé]

#89 #patch (906) Ajout d'une notification mail à chaque commentaire
  db/migrations/000109-01-create-view-user_permissions.js
  db/migrations/000109-02-create-view-shantytown_watchers.js
  server/mails/new_comment.js
  server/models/shantytownComment/create.js
  server/models/shantytownComment/findOne.js
  server/models/shantytownComment/index.js
  server/models/shantytownModel.js
  server/models/userModel.js
  server/services/shantytownComment/createComment.js
  test/suites/server/services/shantytownComment/createComment.spec.js
  test/utils/shantytownComment.js
Labels: [qa]

#91 #patch (1013) Ajout d'un graphique avec l'évolution du nombre d'habitants
  server/controllers/statsController.js
  server/models/statsModel.js
Labels: [validé]
